language: php
sudo: required

branches:
  only:
    - master
    - development
    - travis
env:
  - DOCKER_COMPOSE_VERSION=1.17.1

pre_install:
 - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
 - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
 - sudo apt-get update
 - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
 - sudo /etc/init.d/docker start

install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo /etc/init.d/mysql stop
  - sudo docker-compose -f docker-compose.yml -f docker-compose-production.yml build
  - sudo docker-compose -f docker-compose.yml -f docker-compose-production.yml up -d
  - sleep 9
  - sudo docker ps
  - sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' dockerphp_nginx_1
#  - docker exec -it dockerphp_mysql_1 mysql -e "update user set plugin = 'caching_sha2_password' where user='root';" 
script:
  - php scripts/test.php
