version: '3'
services:
    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        
        ports: 
           - "3306:3306"
        volumes:
           - ./data:/var/lib/mysql
           - ./init:/docker-entrypoint-initdb.d/
        environment:
           - MYSQL_ROOT_PASSWORD=eip2weeYee3gungo9Uphaev4aXo4ePh8

    php:
        build: 
          context: ./php
          dockerfile: Dockerfile
        ports:
           - 9000:9000
        volumes:
           - ./web:/web
        links:
           - mysql


# this might take a minute or two to start up the first time.

# Out of the box configuration is to use a predefined mysql root password. You 
# change the password above look for the MYSQL_ROOT_PASSWORD line or change to
# using a random password. In that case remove the MYSQL_ROOT_PASSWOR directive
# and instead add MYSQL_RANDOM_ROOT_PASSWORD=yes 

# after start up execute docker ps to find the container name
# for mysql. Use that name to execute the following command
#
#   docker logs <mysql-container>  2>&1 | grep GENERATED
# 
# example:
#    docker logs phpmysql_mysql_1  2>&1 | grep GENERATED
#
# use 
# docker exec -it phpmysql_mysql_1 mysql -uroot -p

# to connect to the server.

