version: '2'
services:
    mysql:
        image: mysql
        ports: 
           - "3306:3306"
        volumes:
           - ./data:/var/lib/mysql
           - ./init:/docker-entrypoint-initdb.d/
        environment:
           - MYSQL_RANDOM_ROOT_PASSWORD=YES

    php:
        build: php
        volumes:
           - ./web:/web
           - ./php.ini://usr/local/etc/php/php.ini
        links:
           - mysql
    nginx:
        image: nginx
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./web:/web
          - ./default.conf:/etc/nginx/conf.d/default.conf:ro
          - /var/log:/var/log
          - /tmp:/tmp
          - ./letsencrypt:/letsencrypt"
        links:
          - php


# this might take a minute or two to start up the first time.
# after start up execute docker ps to find the container name
# for mysql. Use that name to execute the following command
#
#   docker logs <mysql-container>  2>&1 | grep GENERATED
# 
# example:
#    docker logs phpmysql_mysql_1  2>&1 | grep GENERATED
#
# use 
# docker exec -it phpmysql_mysql_1 mysql -uroot -p

# to connect to the server.
