version: '3'
services:
    php:
        build:
           context:  ./php
           dockerfile: Dockerfile-production

    nginx:
        image: nginx
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./web:/web
          - ./default.conf:/etc/nginx/conf.d/default.conf:ro
          - /var/log:/var/log
          - /tmp:/tmp
          - ./letsencrypt:/letsencrypt"
        links:
          - php
